# MaisonVerte E15 resource-conscious server settings.
StartPollers=3
StartPollersUnreachable=1
StartPingers=1
StartDiscoverers=1
CacheSize=32M
HistoryCacheSize=16M
HistoryIndexCacheSize=8M
TrendCacheSize=8M
ValueCacheSize=16M
Timeout=4
LogSlowQueries=3000
