[global]
    map to guest = Bad User
    server string = MaisonVerte Marketing Files
    guest account = nobody
    smb ports = 445

[myshare]
    path = /home/share
    read only = no
    guest ok = yes
    guest only = yes
    browseable = yes
    force user = nobody
    create mask = 0777
    directory mask = 0777
    acl allow execute always = yes
